### ISSUE TITLE
Apply latest round of K8's updates for Nessus patches

### ISSUE THREAD

**Issue by pburkholder** [cloud-gov/kubernetes-release#126]
In order to keep Kubernetes patched, we want to address the following findings:

plugin 144011:
```
  - Installed package : curl_7.47.0-1ubuntu2.16
    Fixed package     : curl_7.47.0-1ubuntu2.18

  - Installed package : libcurl3_7.47.0-1ubuntu2.16
    Fixed package     : libcurl3_7.47.0-1ubuntu2.18

  - Installed package : libcurl3-gnutls_7.47.0-1ubuntu2.16
    Fixed package     : libcurl3-gnutls_7.47.0-1ubuntu2.18

  - Installed package : libcurl4-openssl-dev_7.47.0-1ubuntu2.16
    Fixed package     : libcurl4-openssl-dev_7.47.0-1ubuntu2.18
```

plugin 144013:
```
 - Installed package : apt_1.2.32ubuntu0.1
    Fixed package     : apt_1.2.32ubuntu0.2

  - Installed package : apt-utils_1.2.32ubuntu0.1
    Fixed package     : apt-utils_1.2.32ubuntu0.2

  - Installed package : libapt-inst2.0_1.2.32ubuntu0.1
    Fixed package     : libapt-inst2.0_1.2.32ubuntu0.2

  - Installed package : libapt-pkg5.0_1.2.32ubuntu0.1
    Fixed package     : libapt-pkg5.0_1.2.32ubuntu0.2
```

plugin 144015:
```
  - Installed package : python-apt-common_1.1.0~beta1ubuntu0.16.04.9
    Fixed package     : python-apt-common_1.1.0~beta1ubuntu0.16.04.10

  - Installed package : python3-apt_1.1.0~beta1ubuntu0.16.04.9
    Fixed package     : python3-apt_1.1.0~beta1ubuntu0.16.04.10
```

plugin 144337:
```
  - Installed package : unzip_6.0-20ubuntu1
    Fixed package     : unzip_6.0-20ubuntu1.1
```

## Acceptance Criteria

* [ ] GIVEN a new Nessus scan, these plugins are clean.

--- 

## Security considerations

Patching improves securing. The information in this issue is not directly actionable.

**Comment by pburkholder** [comment]
@ChrisMcGowan Can you review a) the latest Nessus results and b) the updates to #cg-compliance at https://gsa-tts.slack.com/archives/C0A1Z7L2U/p1610505195000100 and update the release for those issues?  Then I think we're good to roll.

**Comment by ChrisMcGowan** [comment]
https://ubuntu.com/security/notices/USN-4635-1
- All set - either packages not installed or already at recommenced version 

https://ubuntu.com/security/notices/USN-4660-1
- We are on linux-image-4.15.0-76-generic so NA

https://ubuntu.com/security/notices/USN-4662-1
- added in libssl1.0.0=1.0.2g-1ubuntu4.18 was libssl1.0.0=1.0.2g-1ubuntu4.17

https://ubuntu.com/security/notices/USN-4665-1
- all set with other fixes in this request

https://ubuntu.com/security/notices/USN-4667-1
- all set with other fixes in this request

https://ubuntu.com/security/notices/USN-4668-1
- all set with other fixes in this request

**Comment by ChrisMcGowan** [comment]
@pburkholder - checked Nessus:

- Kernel ones we can't do due to stemcell/kernel verision
- libp11-kit0=0.23.2-5~ubuntu16.04.1 is going to libp11-kit0=0.23.2-5~ubuntu16.04.2
